name: Test job cancel

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print content of github context
      run: |
        cat << 'EOF'
        ${{ toJSON(github) }}
        EOF
        echo ${{ github.ref }} ${{ 'refs/heads/' & githug.event.repository.default_branch }}
        echo ${{ github.ref == 'refs/heads/' & githug.event.repository.default_branch }}
    - name: Check the package is not uploaded yet
      id: check
      run: |
        exit 1
    - name: This shouldn't run
      if: ${{ steps.check.outcome == 'success' }}
      run: echo I am not here
