name: Test job cancel

on:
  - push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Check the package is not uploaded yet
      id: check
      run: |
        exit 1
    - name: This shouldn't run
      if: ${{ steps.check.outcome == 'success' }}
      run: echo I am not here
