name: ConcurrencyCallCheck
concurrency:
  group: dummy-group
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:
    inputs:
      outer-job-name:
        required: true
        type: string
      build-type:
        required: true
        type: string
      runner-type:
        default: ubuntu-latest
        required: false
        type: string
jobs:
  CallTest:
    env:
      GITHUB_FULL_JOB: ${{ inputs.outer-job-name }} / CallTest
    runs-on: ${{inputs.runner-type}}
    name: CallTest${{inputs.build-type}}
    steps:
      - uses: hmarr/debug-action@1201a20fc9d278ddddd5f0f46922d06513892491
