name: ConcurrencyCallCheck
concurrency:
  group: dummy-group
on:  # yamllint disable-line rule:truthy
  workflow_dispatch:
  workflow_call:
    inputs:
      outer-job-name:
        required: true
        type: string
jobs:
  CallTest:
    env:
      GITHUB_JOB: ${{ inputs.outer-job-name }} / CallTest
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@1201a20fc9d278ddddd5f0f46922d06513892491
