name: Get diff of pull-request

on:
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Print content of github context
      run: |
        cat << 'EOF'
        ${{ toJSON(github) }}
        EOF
    - uses: jitterbit/get-changed-files@v1
      id: files
      with:
        format: 'json'
    - run: |
        readarray -t files <<< $(jq -r '.[]|select(. | endswith(".py"))' <<< '${{ steps.files.outputs.added_modified }}')
        for file in ${files[@]}; do
          echo $file
        done
