name: General tests

'on':
  - pull_request
  - push

jobs:
  call_test:
    # This test fails completely
    # https://github.com/orgs/community/discussions/8945
    # https://github.com/actions/runner/issues/2577
    uses: ./.github/workflows/concurrency_call.yml
    with:
      outer-job-name: call_test

  composite_test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build
        uses: ./.github/actions/test_composite

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Print content of github context
        run: |
          cat << 'EOF'
          ${{ toJSON(github) }}
          EOF
          cat << 'EOF'
          ${{ toJSON(runner) }}
          EOF
          cat << 'EOF'
          ${{ toJSON(env) }}
          EOF
          cat << 'EOF'
          ${{ toJSON(job) }}
          EOF
          env | sort
          echo GITHUB_ENV
          cat $GITHUB_ENV
          echo 'GLOBALLY_SET_ENV=abrakadabra' >> $GITHUB_ENV
      - name: Check GITHUB_ENV
        run: |
          env | sort
          echo $GLOBALLY_SET_ENV
          cat << 'EOF'
          ${{ toJSON(env) }}
          EOF
      - name: Fetch base branch
        id: base_branch
        run: |
          git fetch --progress --depth=1 origin ${{ github.base_ref }}
      - name: And finally, diff
        run: git diff --name-only origin/master

  CreateArtifact:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [1, 2]
    steps:
      - run: |
          mkdir -p artifact-${{ matrix.id }}
          echo '{"id": ${{matrix.id}}}' > \
            artifact-${{ matrix.id }}/artifact-${{ matrix.id }}.json
      - uses: actions/upload-artifact@v3
        with:
          name: artifact-${{ matrix.id }}
          path: artifact-${{ matrix.id }}/artifact-${{ matrix.id }}.json

  DownloadArtifacts:
    needs: [CreateArtifact]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: reports-dir
      - run: |
          ls -lRa reports-dir
