on:
  workflow_call:

jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - run: echo ${{ github.job }}
      - uses: ReeganExE/github-action-job-id@v1.0
        with:
          expose-name: true
      - run: env
